services:
  es01:
    container_name: es-01
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.3
    volumes:
      - esdata01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    environment:
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - node.name=es01
      - ELASTIC_PASSWORD=123456
      - bootstrap.memory_lock=false
      - discovery.type=single-node
      - xpack.security.enabled=false
      # - xpack.security.http.ssl.enabled=false
      # - xpack.security.transport.ssl.enabled=false
      - cluster.routing.allocation.disk.watermark.low=5gb
      - cluster.routing.allocation.disk.watermark.high=3gb
      - cluster.routing.allocation.disk.watermark.flood_stage=2gb
      - TZ=Asia/Shanghai
    # mem_limit: 8073741824
    ulimits:
      memlock:
        soft: -1
        hard: -1
    healthcheck:
      test: ["CMD-SHELL", "curl -u elastic:123456 http://localhost:9200"]
      interval: 10s
      timeout: 10s
      retries: 120
    networks:
      - elastic

  kib01:
    image: docker.elastic.co/kibana/kibana:8.11.3
    container_name: kib01
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_URL: http://es01:9200
      ELASTICSEARCH_HOSTS: '["http://es01:9200"]'
    networks:
      - elastic

volumes:
  esdata01:
    driver: local

networks:
  elastic:
    driver: bridge