
services:
  postgres:
    image: postgres:16.8
    container_name: postgres16
    # restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 1qaz@WSX
      POSTGRES_DB: demo4j
